# Data Science 101 B1

## Day 3 Assignment

### Import

In [1]:
import numpy as np

### Questions 1:

**Create a numpy array starting from 2 till 50 with a stepsize of 3.**

In [2]:
print(np.arange(2,51,3))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


### Questions 2:

**Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.**

In [3]:
list_a = []
list_b = []
n = int(input("Number of elements :"))

for i in range(0,n):
    ele_a = int(input())
    ele_b = int(input())
    
    list_a.append(ele_a)
    list_b.append(ele_b)
    
array_a , array_b = np.array(list_a) , np.array(list_b)

array_a , array_b = array_a.astype(np.int32) , array_b.astype(np.int32)

print('\nAccepted arrays :\n',array_a,'\n\n',array_b)
print(type(array_a),type(array_b))

con_array = np.concatenate((array_a,array_b))
print("Concatenate :",con_array)

print("\nSorted arrays :\n\n",np.sort(array_a),'\n\n',np.sort(array_b))

Number of elements :5
1
4
7
9
5
2
3
8
0
6

Accepted arrays :
 [1 7 5 3 0] 

 [4 9 2 8 6]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
Concatenate : [1 7 5 3 0 4 9 2 8 6]

Sorted arrays :

 [0 1 3 5 7] 

 [2 4 6 8 9]


### Questions 3:

**Write a code snippet to find the dimensions of a ndarray and its size.**

In [4]:
arr = np.array([1,2,3,4,5])
print("Dimension",arr.shape)
print("Size",arr.size)

Dimension (5,)
Size 5


### Questions 4:

**How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims**

In [5]:
arr = np.arange(1,11)

print('1-D Array :',arr)

arr_2 = np.reshape(arr,(-1,2))

print('\n1-D Array converted to 2-D Array :\n',arr_2)
print('Dimensions of converted array :',arr_2.shape,'which is 2-D array')

1-D Array : [ 1  2  3  4  5  6  7  8  9 10]

1-D Array converted to 2-D Array :
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Dimensions of converted array : (5, 2) which is 2-D array


### Questions 5:

**Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()**

In [6]:
c = np.array([[1,2],[3,4]])
d = np.array([[5,6],[7,8]])
print('Vertical Stack :\n',np.vstack((c,d)))
print('Horizontal Stack :\n',np.hstack((c,d)))

Vertical Stack :
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack :
 [[1 2 5 6]
 [3 4 7 8]]


### Questions 6:

**How to get unique items and counts of unique items?**

#### Some methods for to get unique items with examples. Also most used method for counting unique items.

**1. Using set()**

In [7]:
lst1 = [1, 2, 2, 3, 3, 4, 5]

unique_lst_1 = set(lst1)

print('Original List :',lst1)
print("Unique Items from original list :",list(unique_lst_1))
print("Count Of Unique Items :",len(unique_lst_1))

Original List : [1, 2, 2, 3, 3, 4, 5]
Unique Items from original list : [1, 2, 3, 4, 5]
Count Of Unique Items : 5


**2.Using Iteration**


In [8]:
lst2 = [20, 20, 30, 30, 40]
unique_lst_2 = []

for i in lst2:
    if i not in unique_lst_2:
        unique_lst_2.append(i)

print('Original List :',lst2)
print("Unique Items from original list :",unique_lst_2)
print("Count Of Unique Items  :",len(unique_lst_2))

Original List : [20, 20, 30, 30, 40]
Unique Items from original list : [20, 30, 40]
Count Of Unique Items  : 3
